let stu=["anjali", 20, "bhopal", 5.5,1,2,3,4]
console.log(stu)
stu.push("cybrom")
console.log(stu)
stu.pop()
console.log(stu)
stu.unshift("LNCT", 28, "btch")
console.log(stu)
stu.shift()
console.log(stu)
let a=stu.slice(1,4)
console.log(a)
stu.splice(1,3)
console.log(stu)
stu.splice(1,0,"shivi")
console.log(stu)